# Generated by Django 2.2 on 2019-12-04 14:01

import ckeditor.fields
from django.db import migrations, models
import read_statistics.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='新闻标题')),
                ('content', ckeditor.fields.RichTextField(max_length=3000, verbose_name='新闻内容')),
                ('category', models.CharField(max_length=10, verbose_name='新闻类型')),
                ('time', models.DateTimeField(max_length=600, verbose_name='时间')),
            ],
            options={
                'verbose_name': '突发事件新闻',
                'verbose_name_plural': '突发事件新闻',
                'ordering': ['-id'],
            },
            bases=(models.Model, read_statistics.models.ReadNumExpandMethod),
        ),
    ]
